### ISSUE TITLE
androidstudio 6.0手机启动出现的异常

### ISSUE THREAD

**Issue by LearKoo** [wuhaoyu1990/MagicCamera#14]
`Process: com.seu.magiccamera, PID: 3023
                                                                   Theme: themes:{default=overlay:com.h2os.youlun, iconPack:com.h2os.youlun, fontPkg:com.h2os.youlun, com.android.systemui=overlay:com.h2os.youlun, com.android.systemui.navbar=overlay:com.h2os.youlun}
                                                                   java.lang.RuntimeException: Unable to resume activity {com.seu.magiccamera/com.seu.magiccamera.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference
                                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3137)
                                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3168)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2515)
                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                       at android.os.Looper.loop(Looper.java:148)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5456)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference
                                                                       at com.seu.magicfilter.camera.CameraEngine.getPreviewSize(CameraEngine.java:72)
                                                                       at com.seu.magicfilter.camera.CameraEngine.getCameraInfo(CameraEngine.java:111)
                                                                       at com.seu.magicfilter.widget.MagicCameraView.openCamera(MagicCameraView.java:154)
                                                                       at com.seu.magicfilter.widget.MagicCameraView.onResume(MagicCameraView.java:187)
                                                                       at com.seu.magicfilter.MagicEngine.onResume(MagicEngine.java:32)
                                                                       at com.seu.magiccamera.MainActivity.onResume(MainActivity.java:84)
                                                                       at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1259)
                                                                       at android.app.Activity.performResume(Activity.java:6327)
                                                                       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3126)
                                                                       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3168) 
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2515) 
                                                                       at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                       at android.os.Looper.loop(Looper.java:148) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5456) `

**Comment by wuhaoyu1990** [comment]
fixed
