### ISSUE TITLE
android 6.0点击打开相机就挂了

### ISSUE THREAD

**Issue by shizhen2016** [wuhaoyu1990/MagicCamera#58]
相关错误如下
java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference
	at com.seu.magicfilter.camera.CameraEngine.getPreviewSize(CameraEngine.java:97)
	at com.seu.magicfilter.display.MagicCameraDisplay$3.run(MagicCameraDisplay.java:103)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1472)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1249)

**Comment by shizhen2016** [comment]
是在华为mate8上调式的
