### ISSUE TITLE
前置摄像头录制视屏崩溃

### ISSUE THREAD

**Issue by traywangjun** [wuhaoyu1990/MagicCamera#83]

**Comment by traywangjun** [comment]
Process: com.seu.magiccamera, PID: 20958
                                                                     android.media.MediaCodec$CodecException: Error 0xffffec77
                                                                         at android.media.MediaCodec.native_configure(Native Method)
                                                                         at android.media.MediaCodec.configure(MediaCodec.java:1778)
                                                                         at com.seu.magicfilter.encoder.video.VideoEncoderCore.<init>(VideoEncoderCore.java:78)
                                                                         at com.seu.magicfilter.encoder.video.TextureMovieEncoder.prepareEncoder(TextureMovieEncoder.java:397)
                                                                         at com.seu.magicfilter.encoder.video.TextureMovieEncoder.handleStartRecording(TextureMovieEncoder.java:319)
                                                                         at com.seu.magicfilter.encoder.video.TextureMovieEncoder.access$000(TextureMovieEncoder.java:63)
                                                                         at com.seu.magicfilter.encoder.video.TextureMovieEncoder$EncoderHandler.handleMessage(TextureMovieEncoder.java:289)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:148)
                                                                         at com.seu.magicfilter.encoder.video.TextureMovieEncoder.run(TextureMovieEncoder.java:256)
                                                                         at java.lang.Thread.run(Thread.java:818)
